### ISSUE TITLE
nowiki element skipped

### ISSUE THREAD

**Issue by krichter722** [projectgus/yamdwe#14]
The following test case shows disappearance of a `nowiki` element in a list:

    $ python wikicontent_tests.py 
    Running /mnt/DATA/sources/yamdwe/tests/accented_links...
    Running /mnt/DATA/sources/yamdwe/tests/named_links...
    Running /mnt/DATA/sources/yamdwe/tests/tags_in_lists...
    OUTPUT MISMATCH
    Test notes:
    From https://github.com/projectgus/yamdwe/issues/7

    ****************************************
    Input Mediawiki:
    <ul>
    <li><nowiki><nowiki></nowiki></li>
    </ul>

    ****************************************
    Expected Output:
    ****************************************
      * <nowiki><nowiki></nowiki>

    ****************************************
    Actual Output:

      * <nowiki>

    ****************************************
    Running /mnt/DATA/sources/yamdwe/tests/unicode_support...
    --- 3/4 TESTS PASSED ---

**Comment by projectgus** [comment]
Are you able to supply a copy of the full mediawiki page you have that breaks so badly? I can't reproduce the problems you're seeing with simple test cases, it must be something about the structure of the page.

If you don't want to post it publically then you could email it to me - gus at projectgus dot com.

Angus

**Comment by projectgus** [comment]
I think this is properly fixed now, the new solution is a bit more robust - anything in a <nowiki> tag is kept verbatim and just copied into the dokuwiki output.

Let me know if there are any cases this doesn't fix. Sorry for the slow response.
