### ISSUE TITLE
Handle internal anchor links

### ISSUE THREAD

**Issue by krichter722** [projectgus/yamdwe#17]
Mediawiki provides anchor for every section of an article which can be referenced in the form `[[#section]]`, dokuwiki doesn't provide anchors by default, support depends on the [anchor plugin][1]. 

Currently anchor links in MediaWiki are simply transformed as if they were links to articles, e.g. `[[#glassfish - Tips - JVM options]]` becomes `[[_glassfish_tips_jvm_options]]` in dokuwiki which is just not right. Possible solutions and workarounds include:

  * make application of `yamdwe` dependent of presence of anchor plugin and add anchors for every section or those which are referenced (the former shouldn't hurt too much, the latter might be difficult)
  * identify anchor links as those which contain `#` and skip creations for intra page links and remove anchor specification for inter page links (e.g. link to `article` when a link to `article#anchor` is encountered).

[1]: https://www.dokuwiki.org/plugin:anchor

**Comment by projectgus** [comment]
I'm a little confused by your comment, can you please confirm if this is still an issue for you?

With the latest changes I see MediaWiki content of [[#Heading 1]] converted to [[#heading_1]], in a simple test case.

**Comment by krichter722** [comment]
You're right the issue, I could not reproduce the issue for `[#header_1]]`, but headers which contain uppercase letters or `-` cause trouble, see the test case in the referenced pull request.

**Comment by projectgus** [comment]
Sorry for the long delay in replying. I think this commit should fix these problems, header names now go through different processing to page names whereas before they were being treated the same.

Let me know if you find any more broken cases, though. Feel free to re-open this issue or start a new one.
