### ISSUE TITLE
Nested lists don't transform correctly

### ISSUE THREAD

**Issue by krichter722** [projectgus/yamdwe#18]
Unfortunately I have to report the errornous transformation of 

    === Dokuwiki RefNotes plugin - Issues ===
    <ul>
    <li>referencing invalid BibTex keys
      <ul>
      <li>containing <tt>-</tt></li>
      </ul>
      causes silent failure</li>
    </ul>

without a markup sniplet how it is supposed to be correct (I requested an example to make nested list understandable in a comment on https://www.dokuwiki.org/plugin:lists#example_or_clearification_regarding_continuing_list_items_after_a_nested_list). Currently the markup above is transformed into 

      * referencing invalid BibTex keys
      
          * containing ''-''
      
      causes 

which 

  1. creates a list with two items on the same level and
  2. the first item is not continued

**Comment by projectgus** [comment]
I think this is probably not something yamdwe can support - given it requires a plugin, and even then as you point out it's not clear. Probably one for manual cleanup after you import the wiki, sorry.
