### ISSUE TITLE
setup travis-ci integration

### ISSUE THREAD

**Issue by krichter722** [projectgus/yamdwe#25]
I tried to figure out how to setup travis-ci integration. The `.travis.yml` I created in #24 fails with 

    mkvirtualenv --system-site-packages yamdwe
    Using real prefix '/opt/python/2.7.9'
    New python executable in yamdwe/bin/python
    Installing setuptools, pip...done.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named virtualenvwrapper.hook_loader

If you don't like it, just close it.

**Comment by projectgus** [comment]
Nice idea!

As far as I understand it, Travis already runs your project in a sandbox. The virtualenv/virtualenvwrapper stuff is really just for sandboxing yamdwe prerequisites away from system Python stuff.

So I think probably you can remove the virtualenv-related lines from the travis config, and just install everything in the "system" root (which is itself being sandboxed somehow by Travis).


Angus
