### ISSUE TITLE
JSON decoder error

### ISSUE THREAD

**Issue by Bgs4269** [projectgus/yamdwe#31]
I'm trying to export from our mediawiki. I get the following error:
 simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
Which stems from simplejson decoder.py line 400.

I have no info what source triggered this, but if you tell me how to get it, I will.

Additional info:
- Cloned from github.

**Comment by projectgus** [comment]
Hi Bgs,

Thanks for letting me know about the error.

It looks like for some reason the mediawiki API is sending malformed JSON. The JSON spec is pretty simple and the parser we use is built into Python so pretty mature, which makes me think it's probably a problem with the mediawiki API somehow - or maybe it's throwing an error of some kind in a non-JSON format.

Are you able to copy the entire output of yamdwe including the error, for some context?

A couple other questions: What version of Mediawiki are you running? Is the wiki you're exporting publically available by any chance?


Angus

**Comment by projectgus** [comment]
Actually on second thought the fact that the error is coming at line 2 char 1 makes me think that the API isn't returning valid JSON at all, but perhaps a text error message or something else.

Can you also post the output of loading this URL on your wiki, in a browser?
/api.php?format=json&action=query&meta=siteinfo

(For any long output you need to post, please use pastebin.com or gist.github.com and send a link.)

Cheers!

**Comment by Bgs4269** [comment]
Hello Angus,

I'm afraid the wiki is a closed one. I used the urlpath below and got 
the following (obfuscated with same amount of x'es where due):

{"query":{"general":{"mainpage":"Kezd\u0151lap","base":"https:\/\/wiki.xxxxxxxxxxx.xx\/index.php\/Kezd%C5%91lap","sitename":"XXXXWiki","generator":"MediaWiki 1.9.2","case":"first-letter","rights":""}}}


Could it be the character coding? We have both \0151 and %C5C91

Best regards
Zoltán

**Comment by projectgus** [comment]
Hi Zoltan,

Sorry for the slow reply, thanks for checking that output.

The character encoding might be the issue, it's possible the Python JSON parser is choking on it somehow.

To re-ask an earlier question, do you get any other output from yamdwe at all, apart from the error?

Angus

**Comment by Bgs4269** [comment]
Hello Angus,

Here is the output:

bgs@wiki ~/wiki/yamwde/yamdwe % ./yamdwe.py --http_user myuser --wiki_user myuser http://wiki.mycompany.com /home/bgs/wiki/dokuwiki                 
Enter password for HTTP auth (myuser): 
Enter password for Wiki login (myuser): 
Logging in as myuser... 
Traceback (most recent call last):
  File "./yamdwe.py", line 93, in <module>
    main()
  File "./yamdwe.py", line 37, in main
    importer = mediawiki.Importer(args.mediawiki, args.http_user, args.http_pass, args.wiki_user, args.wiki_pass)
  File "/home/bgs/wiki/yamwde/yamdwe/mediawiki.py", line 19, in __init__
    if not self.mw.login(wiki_user, wiki_pass):
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplemediawiki.py", line 251, in login
    return do_login(self, user, passwd)
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplemediawiki.py", line 242, in do_login
    result = self.call(data)
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplemediawiki.py", line 184, in call
    return json.loads(self._fetch_http(self._api_url, params))
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

Does it help to find the problem?

Best regards
Zoltán

**Comment by projectgus** [comment]
Ah, I see now. Does the URL you're passing to yamdwe.py look like http://wiki.mycompany.com ? The URL passed to yamdwe has to be the URL to Mediawiki API, so it's probably something like http://wiki.mycompany.com/api.php or http://wiki.mycompany.com/w/api.php or similar.

(If you load the API URL in your browser, it will look something like this: https://fedoraproject.org/w/api.php )

**Comment by Bgs4269** [comment]
I forgot the /api.php this time, but with it, I get the same result:

Traceback (most recent call last):
  File "./yamdwe.py", line 93, in <module>
    main()
  File "./yamdwe.py", line 37, in main
    importer = mediawiki.Importer(args.mediawiki, args.http_user, args.http_pass, args.wiki_user, args.wiki_pass)
  File "/home/bgs/wiki/yamwde/yamdwe/mediawiki.py", line 19, in __init__
    if not self.mw.login(wiki_user, wiki_pass):
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplemediawiki.py", line 251, in login
    return do_login(self, user, passwd)
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplemediawiki.py", line 242, in do_login
    result = self.call(data)
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplemediawiki.py", line 184, in call
    return json.loads(self._fetch_http(self._api_url, params))
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/bgs/.virtualenvs/yamdwe/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

The api.php works. Opening it with a browser I get a normal xml output. First few lines:
<?xml version="1.0" encoding="utf-8"?>
<api>
  <error code="help" info="">

The above in json, can be found here: http://pastebin.com/aJuJmuJv

**Comment by projectgus** [comment]
I should have noticed this earlier, but I just saw from the api.php output that you're using Mediawiki version 1.9.2 (June 2007).

Yamdwe only supports Mediawiki 1.13 or newer. If you upgrade your Mediawiki install to a recent version first, then you should be able to export via yamdwe.

**Comment by Bgs4269** [comment]
I missed that too. :(
Happily closing the ticket.

**Comment by vivideo** [comment]
Hi!
Using Mediawiki 1.25.1 I got almost the same error as Bgs4269 while migrating the mediawiki content to a new docuwiki installation. This is the output:

> Traceback (most recent call last):
>   File "yamdwe.py", line 93, in <module>
>     main()
>   File "yamdwe.py", line 41, in main
>     importer = mediawiki.Importer(args.mediawiki, args.http_user, args.http_pass, args.wiki_user, args.wiki_pass, args.verbose)
>   File "/home/myname/env/yamdwe/mediawiki.py", line 20, in __init__
>     if not self.mw.login(wiki_user, wiki_pass):
>   File "/home/myname/env/local/lib/python2.7/site-packages/simplemediawiki.py", line 251, in login
>     return do_login(self, user, passwd)
>   File "/home/myname/env/local/lib/python2.7/site-packages/simplemediawiki.py", line 242, in do_login
>     result = self.call(data)
>   File "/home/myname/env/local/lib/python2.7/site-packages/simplemediawiki.py", line 184, in call
>     return json.loads(self._fetch_http(self._api_url, params))
>   File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode(s)
>   File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
> simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Can you see what's going wrong?

Cheers :)

**Comment by projectgus** [comment]
Is the URL you're passing the URL of the API?

Quoting from above:
> Does the URL you're passing to yamdwe.py look like http://wiki.mycompany.com ? The URL passed 
> to yamdwe has to be the URL to Mediawiki API, so it's probably something like 
> http://wiki.mycompany.com/api.php or http://wiki.mycompany.com/w/api.php or similar.
> 
> (If you load the API URL in your browser, it will look something like this: https://fedoraproject.org/w/api.php )
