### ISSUE TITLE
The page numbers

### ISSUE THREAD

**Issue by vinhnguyen116** [projectgus/yamdwe#37]
Hello,
I try to convert my media wiki with the result: Found 306 pages to export...and it convert 306 pages successfully.
But when i browsed the Special:Statistics page of the media site i got message as below:
"There are 13,678 total pages in the database. This includes "talk" pages, pages about WikiWin, minimal "stub" pages, redirects, and others that probably do not qualify as content pages. Excluding those, there are 1,707 pages that are probably legitimate content pages. "

The number of content page of this site: 1707 pages but the tool found 306 pages
Could you help me explain it ? did i convert total of pages completely?

Thank you so much
Vinh

**Comment by projectgus** [comment]
I've never heard of a wiki that large being converted, so there might be a bug where API is only returning the first 306 pages and needs another query to return the rest.

Are there missing pages in the converted wiki?

Any chance the wiki is publically available to access?

**Comment by vinhnguyen116** [comment]
Hello,
Thank for your reply, i recheck on my side. maybe i misunderstand
Additional, do you know how to get exactly the number of pages (content) on media wiki ? because i got the number from the statistic page as previous post. I think it not exactly the number of page need to converted to dokuwiki. (1,707 pages ).

Thank you
Vinh

**Comment by projectgus** [comment]
Yamdwe uses the mediawiki API to get the number of pages. I don't know of any other way to see it in a browser, except for the Statistics page.

**Comment by vinhnguyen116** [comment]
Thank you so much.
